/**
 * File generated by Magnet rest2mobile 1.1 - 20 nov. 2014 18:43:10
 * @see {@link http://developer.magnet.com}
 */

package youp.ingesup.com.youp.model.bean;


/**
 * Generated from json example
{
  "Id" : 1,
  "Ville" : "samplestring2",
  "CodePostale" : "samplestring3",
  "Adresse" : "samplestring4",
  "Longitude" : 5.0,
  "Latitude" : 6.0,
  "Pays" : "samplestring7",
  "Nom" : "samplestring8"
}

 */

public class Adresse {

  
@com.google.gson.annotations.SerializedName("Adresse")
  private String adresse;

  
@com.google.gson.annotations.SerializedName("CodePostale")
  private String codePostale;

  
@com.google.gson.annotations.SerializedName("Id")
  private Integer id;

  
@com.google.gson.annotations.SerializedName("Latitude")
  private Double latitude;

  
@com.google.gson.annotations.SerializedName("Longitude")
  private Double longitude;

  
@com.google.gson.annotations.SerializedName("Nom")
  private String nom;

  
@com.google.gson.annotations.SerializedName("Pays")
  private String pays;

  
@com.google.gson.annotations.SerializedName("Ville")
  private String ville;

  public String getAdresse() {
    return adresse;
  }
  public String getCodePostale() {
    return codePostale;
  }
  public Integer getId() {
    return id;
  }
  public Double getLatitude() {
    return latitude;
  }
  public Double getLongitude() {
    return longitude;
  }
  public String getNom() {
    return nom;
  }
  public String getPays() {
    return pays;
  }
  public String getVille() {
    return ville;
  }

  /**
  * Builder for Adresse
  **/
  public static class AdresseBuilder {
    private Adresse toBuild = new Adresse();

    public AdresseBuilder() {
    }

    public Adresse build() {
      return toBuild;
    }

    public AdresseBuilder adresse(String value) {
      toBuild.adresse = value;
      return this;
    }
    public AdresseBuilder codePostale(String value) {
      toBuild.codePostale = value;
      return this;
    }
    public AdresseBuilder id(Integer value) {
      toBuild.id = value;
      return this;
    }
    public AdresseBuilder latitude(Double value) {
      toBuild.latitude = value;
      return this;
    }
    public AdresseBuilder longitude(Double value) {
      toBuild.longitude = value;
      return this;
    }
    public AdresseBuilder nom(String value) {
      toBuild.nom = value;
      return this;
    }
    public AdresseBuilder pays(String value) {
      toBuild.pays = value;
      return this;
    }
    public AdresseBuilder ville(String value) {
      toBuild.ville = value;
      return this;
    }
  }
}
