/**
 * File generated by Magnet rest2mobile 1.1 - 20 nov. 2014 18:16:37
 * @see {@link http://developer.magnet.com}
 */

package youp.ingesup.com.youp.model.bean;


/**
 * Generated from json example
{
  "Categorie_id" : 1,
  "Libelle" : "samplestring2"
}

 */

public class Category {

  
@com.google.gson.annotations.SerializedName("Categorie_id")
  private Integer categorie_id;

  
@com.google.gson.annotations.SerializedName("Libelle")
  private String libelle;

  public Integer getCategorie_id() {
    return categorie_id;
  }
  public String getLibelle() {
    return libelle;
  }

  /**
  * Builder for Category
  **/
  public static class CategoryBuilder {
    private Category toBuild = new Category();

    public CategoryBuilder() {
    }

    public Category build() {
      return toBuild;
    }

    public CategoryBuilder categorie_id(Integer value) {
      toBuild.categorie_id = value;
      return this;
    }
    public CategoryBuilder libelle(String value) {
      toBuild.libelle = value;
      return this;
    }
  }
}
