/**
 * File generated by Magnet rest2mobile 1.1 - 21 nov. 2014 09:34:29
 * @see {@link http://developer.magnet.com}
 */

package youp.ingesup.com.youp.model.bean;


/**
 * Generated from json example
{
  "Nom" : 11,
  "Id" : 1
}

 */

public class EtatEvenement {

  
@com.google.gson.annotations.SerializedName("Id")
  private Integer id;

  
@com.google.gson.annotations.SerializedName("Nom")
  private Integer nom;

  public Integer getId() {
    return id;
  }
  public Integer getNom() {
    return nom;
  }

  /**
  * Builder for EtatEvenement
  **/
  public static class EtatEvenementBuilder {
    private EtatEvenement toBuild = new EtatEvenement();

    public EtatEvenementBuilder() {
    }

    public EtatEvenement build() {
      return toBuild;
    }

    public EtatEvenementBuilder id(Integer value) {
      toBuild.id = value;
      return this;
    }
    public EtatEvenementBuilder nom(Integer value) {
      toBuild.nom = value;
      return this;
    }
  }
}
