/**
 * File generated by Magnet rest2mobile 1.1 - 21 nov. 2014 09:34:29
 * @see {@link http://developer.magnet.com}
 */

package youp.ingesup.com.youp.model.bean;


/**
 * Generated from json example
{
  "Url" : "samplestring1",
  "Id" : 2,
  "EvenementId" : 3
}

 */

public class Gallery {

  
@com.google.gson.annotations.SerializedName("EvenementId")
  private Integer evenementId;

  
@com.google.gson.annotations.SerializedName("Id")
  private Integer id;

  
@com.google.gson.annotations.SerializedName("Url")
  private String url;

  public Integer getEvenementId() {
    return evenementId;
  }
  public Integer getId() {
    return id;
  }
  public String getUrl() {
    return url;
  }

  /**
  * Builder for Gallery
  **/
  public static class GalleryBuilder {
    private Gallery toBuild = new Gallery();

    public GalleryBuilder() {
    }

    public Gallery build() {
      return toBuild;
    }

    public GalleryBuilder evenementId(Integer value) {
      toBuild.evenementId = value;
      return this;
    }
    public GalleryBuilder id(Integer value) {
      toBuild.id = value;
      return this;
    }
    public GalleryBuilder url(String value) {
      toBuild.url = value;
      return this;
    }
  }
}
